### ISSUE TITLE
Does not conform to Markdown spec on link label matching

### ISSUE THREAD

**Issue by jaens** [syntax-tree/mdast-util-definitions#4]
The current normalization algorithm just converts the string to uppercase, as far as I see.

The Markdown spec says the following about matching link labels:

>  To normalize a label, strip off the opening and closing brackets, perform the Unicode case fold, strip leading and trailing whitespace and collapse consecutive internal whitespace to a single space.

It would probably be useful to follow that since I imagine this plugin is often used for connecting link definitions and reference links.

**Comment by wooorm** [comment]
In mdast, `identifier` [should already be normalized](https://github.com/syntax-tree/mdast#association), the normalizing going on here is to prevent an identifier of `constructor` or `toString` to mess with the object we’re using.

> It would probably be useful to follow that

It would also be pretty useful to follow [the issue template](https://raw.githubusercontent.com/syntax-tree/.github/master/.github/ISSUE_TEMPLATE/1-bug.md) that you picked but removed, it greatly helps us help you. 😬

**Comment by jaens** [comment]
None of the questions in the template really made any sense for this specific issue (except "Subject"), as this is purely about the design of the API.

The problem is only *one* side of the matched identifier is guaranteed to come from an `identifier` - the caller of `definition()` can pass in any arbitrary string.

If the caller passes in a string with eg. multiple consecutive whitespaces or trailing/leading whitespace, then the current implementation is *guaranteed* to fail, as there's no way it can match to anything.

That's probably a surprising gotcha, since the implementation already does *some* normalization, so it seems weird to leave "half" of it to the caller (also considering that using mismatching normalization algorithms will lead to failure situations like I described above).

**Comment by wooorm** [comment]
> as this is purely about the design of the API.

Those questions are there to decrease time spent going back-and-forth, e.g., resolving the [XY problem](https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem) that I’m sensing here. Seeing some code, or hearing about how you ran into this, would help.

> the caller of `definition()` can pass in any arbitrary string.

Right, you could also pass a number, a boolean, or an object, but the docs specifically mention `identifier`, so the code assumes it is indeed a conforming identifier.

The “normalise” function here is confusingly named, true, but again: it solves prototype pollution.

This project doesn’t have any knowledge of how parsing of identifiers happens, e.g., whether parsing of identifiers supports character references or backslash escapes. This is currently not the case, but a flavor of Markdown could support it, or a userland plugin could do it. In which case, we’d have to update the code here too, or be incompatible.

```
[a][b\<c]

[b<c]: example.com
```

In this project, we only assume that identifiers are case-insensitive, and I think we shouldn’t do more.

**Comment by wooorm** [comment]
I think the current behavior is fine, as detailed in my comments above. If you disagree, please comment here!
